using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum ConfigurationDataValueName
{
    EasyEnemyMinShotDelay,
    MediumEnemyMinShotDelay,
    HardEnemyMinShotDelay,
    EasyEnemyMaxShotDelay,
    MediumEnemyMaxShotDelay,
    HardEnemyMaxShotDelay,
    EasyEnemyHomingDelay,
    MediumEnemyHomingDelay,
    HardEnemyHomingDelay,
    EasyEnemyProjectileHomingDelay,
    MediumEnemyProjectileHomingDelay,
    HardEnemyProjectileHomingDelay,

    HomingDelayEnemy_0,
    HomingDelayEnemy_1,
    HomingDelayEnemy_2,
    HomingDelayEnemy_3,
    HomingDelayEnemy_4,
    HomingDelayEnemy_5,
    HomingDelayEnemy_6,
    HomingDelayEnemy_7,
    HomingDelayEnemy_8,
    HomingDelayEnemy_9,
    HomingDelayEnemy_10,

    ShotDelayEnemy_0,
    ShotDelayEnemy_1,
    ShotDelayEnemy_2,
    ShotDelayEnemy_3,
    ShotDelayEnemy_4,
    ShotDelayEnemy_5,
    ShotDelayEnemy_6,
    ShotDelayEnemy_7,
    ShotDelayEnemy_8,
    ShotDelayEnemy_9,
    ShotDelayEnemy_10,

    SpawnRateEnemy_0,
    SpawnRateEnemy_1,
    SpawnRateEnemy_2,
    SpawnRateEnemy_3,
    SpawnRateEnemy_4,
    SpawnRateEnemy_5,
    SpawnRateEnemy_6,
    SpawnRateEnemy_7,
    SpawnRateEnemy_8,
    SpawnRateEnemy_9,
    SpawnRateEnemy_10,

    MinImpulseForceEnemy_0,
    MinImpulseForceEnemy_1,
    MinImpulseForceEnemy_2,
    MinImpulseForceEnemy_3,
    MinImpulseForceEnemy_4,
    MinImpulseForceEnemy_5,
    MinImpulseForceEnemy_6,
    MinImpulseForceEnemy_7,
    MinImpulseForceEnemy_8,
    MinImpulseForceEnemy_9,
    MinImpulseForceEnemy_10,

    MaxImpulseForceEnemy_0,
    MaxImpulseForceEnemy_1,
    MaxImpulseForceEnemy_2,
    MaxImpulseForceEnemy_3,
    MaxImpulseForceEnemy_4,
    MaxImpulseForceEnemy_5,
    MaxImpulseForceEnemy_6,
    MaxImpulseForceEnemy_7,
    MaxImpulseForceEnemy_8,
    MaxImpulseForceEnemy_9,
    MaxImpulseForceEnemy_10,

    ProjectileSpeedEnemy_0,
    ProjectileSpeedEnemy_1,
    ProjectileSpeedEnemy_2,
    ProjectileSpeedEnemy_3,
    ProjectileSpeedEnemy_4,
    ProjectileSpeedEnemy_5,
    ProjectileSpeedEnemy_6,
    ProjectileSpeedEnemy_7,
    ProjectileSpeedEnemy_8,
    ProjectileSpeedEnemy_9,
    ProjectileSpeedEnemy_10
}
